version: 2
jobs:
  build:
    docker:
      #
      - image: circleci/node:10.16
      - image: circleci/postgres:11.3
        environment:
          POSTGRES_USER: root
          POSTGRES_DB: circle_test

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    environment:
      NODE_ENV: test
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: Install all packages
          command: npm install && npm run install:all

      - run:
          name: Migrate database
          environment:
            DATABASE_TEST_USERNAME: root
            DATABASE_TEST_NAME: circle_test
            DATABASE_HOST: localhost
          command: cd ./packages/backend && npm run migrate

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
      - run: npm test
